import Head from 'next/head';
import { Lato } from 'next/font/google';

const lato = Lato({ weight: '400', subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Called Quicks</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${lato.className} row bg-primary-1`}></main>
        </>
    );
}
