import Head from 'next/head';
import { Lato } from 'next/font/google';

const lato = Lato({ weight: '400', subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${lato.className} row`}>
                <div className="col-1 bg-chat-0">
                    <h1>lato lato</h1>
                </div>
                <div className="col-12 bg-stickers-3">aa</div>
                <div className="col-8 bg-primary-0">bb</div>
                <div className="col bg-chats-shade-0 primary-0">cc</div>
                <div className="col ma-lg">dd</div>
            </main>
        </>
    );
}
